# Generated by Django 3.2.5 on 2021-08-17 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20210814_2032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-votes_ratio', '-votes_total', 'title']},
        ),
    ]
